/**
 * Writes README.md into the output folder: every file, its pixel size, bytes
 * and intended slot, plus the headline copy per language.
 *   node scripts/promo/readme.mjs [outDir]
 */
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join, relative, extname } from 'path';
import { homedir } from 'os';
import { execFileSync } from 'child_process';
import { COPY } from './copy.mjs';

const pngSize = (f) => {
  const b = readFileSync(f);
  return `${b.readUInt32BE(16)}×${b.readUInt32BE(20)}`;
};
const kb = (n) => (n > 1024 * 1024 ? `${(n / 1024 / 1024).toFixed(1)} MB` : `${Math.round(n / 1024)} KB`);

function videoInfo(f, ffmpeg) {
  if (!ffmpeg) return '';
  try {
    execFileSync(ffmpeg, ['-hide_banner', '-i', f], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    const s = String(e.stderr ?? '');
    const dur = /Duration: (\d+):(\d+):([\d.]+)/.exec(s);
    const dim = /Video: (\w+).*?, (\d{3,4})x(\d{3,4})/.exec(s);
    const secs = dur ? (+dur[1] * 3600 + +dur[2] * 60 + +dur[3]).toFixed(1) : '?';
    return dim ? `${dim[2]}×${dim[3]} ${dim[1]} · ${secs}s` : `${secs}s`;
  }
  return '';
}

function use(rel) {
  const n = rel.replace(/\\/g, '/');
  if (n.startsWith('play/phone-')) return 'Google Play — phone screenshot (listing order = number)';
  if (n.startsWith('play/feature-graphic')) return 'Google Play — feature graphic';
  if (n.startsWith('play/tablet-')) return 'Google Play — 7"/10" tablet screenshot (desktop layout)';
  if (n.startsWith('sns/feed/') && n.includes('overview')) return 'Instagram feed 4:5 — all five tabs (carousel cover)';
  if (n.startsWith('sns/feed/')) return 'Instagram feed 4:5 — one tab';
  if (n.startsWith('sns/story/')) return 'Instagram story / reel cover 9:16';
  if (n.startsWith('video/reel-')) return 'Instagram Reel / Shorts / Play promo — title card + 5 tabs + end card';
  if (n.startsWith('video/') && n.endsWith('.mp4')) return 'Reel / Story clip 9:16, framed with headline';
  if (n.startsWith('video/') && n.endsWith('.webm')) return 'Raw phone screen recording (for editing)';
  if (n.startsWith('raw/phone-')) return 'Raw app capture, 390×844 @3x (source for composites)';
  if (n.startsWith('raw/desk-')) return 'Raw desktop capture, 1600×1000 @1.5x';
  return '';
}

export function writeReadme(OUT, ffmpeg) {
  const files = [];
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) { if (!e.name.startsWith('_')) walk(p); } else if (e.name !== 'README.md') files.push(p);
    }
  };
  walk(OUT);
  files.sort();
  const rows = files.map((f) => {
    const rel = relative(OUT, f).replace(/\\/g, '/');
    const ext = extname(f);
    const spec = ext === '.png' ? `${pngSize(f)} PNG` : ext === '.mp4' || ext === '.webm' ? videoInfo(f, ffmpeg) : ext.slice(1);
    return `| \`${rel}\` | ${spec} | ${kb(statSync(f).size)} | ${use(rel)} |`;
  });
  const copyRows = Object.entries(COPY).map(([k, v]) => `| ${k} | ${v.ko[0].replace(/\n/g, ' ')} — ${v.ko[1]} | ${v.en[0]} — ${v.en[1]} |`);
  const md = `# 24Houring promo assets — 2026-09

Generated by \`scripts/promo/build.mjs\` from the real app (built \`dist/\`, fully offline, all \`/api\` mocked)
filled with fictional sample data (\`scripts/promo/data.mjs\`): a 35-year-old office worker's weekday, a month
of plans with a Jeju trip, a life line from 1991 with her mother's line beside it, 16 people in family / friends /
work with subgroups and ties, 12 visited + 5 wished countries and 12 pins. Korean (\`ko\`) and English (\`en\`).

Regenerate: \`npm run build && node scripts/promo/build.mjs\` (options: \`--phase=shots,tablet,compose,video\`,
\`--lang=ko,en\`, \`--only=<tab>\`; env \`PROMO_DIST\`, \`PROMO_OUT\`, \`FFMPEG\`, \`PROMO_REAL_TILES=1\`).

Notes
- Google Play accepts up to 8 phone screenshots per language: \`play/phone-<lang>-01…08\` are in listing order.
- The pin-map tiles are a locally drawn stand-in (Natural Earth outlines), not OpenStreetMap, because the build is
  offline; the OSM credit is hidden in those captures. Rerun with \`PROMO_REAL_TILES=1\` to use real OSM tiles.
- Status bar (14:20, signal, battery) in the phone frame is decorative.

## Files

| File | Spec | Size | Intended use |
|---|---|---|---|
${rows.join('\n')}

## Headline copy

| Key | 한국어 | English |
|---|---|---|
${copyRows.join('\n')}
`;
  writeFileSync(join(OUT, 'README.md'), md);
  return files.length;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) {
  const out = process.argv[2] || join(homedir(), 'Desktop', '24houring_playstore', 'promo-2026-09');
  const { findFfmpeg } = await import('./video.mjs');
  console.log('README rows:', writeReadme(out, findFfmpeg().h264 ?? findFfmpeg().vp8));
}
