/**
 * Legacy article URLs → the pillar that absorbed them.
 *
 * GENERATED by scripts/gen-pillars.mjs from each pillar's `absorbs` list —
 * edit the pillar JSON and re-run, do not hand-edit this file.
 *
 * The 40 thin /health and /stories pages were consolidated into 10 deep pillars.
 * Workers static assets cannot 301 on their own, so wrangler.jsonc routes
 * /health/* and /stories/* through the Worker first and it answers these paths
 * with a real 301; the old URLs pass their ranking on and no thin page ships.
 *
 * Kept as a plain map (not a prefix rule) so a typo can never redirect a pillar
 * onto itself — see worker/__tests__/legacy-redirects.test.ts.
 */
export const LEGACY_REDIRECTS: Readonly<Record<string, string>> = {
  '/health/avoid-late-night-eating': '/health/nutrition',
  '/health/avoid-prolonged-sitting': '/health/movement',
  '/health/breakfast-and-energy': '/health/nutrition',
  '/health/caffeine-timing': '/health/rhythm',
  '/health/consistent-daily-routine': '/health/rhythm',
  '/health/daily-walk': '/health/movement',
  '/health/everyday-movement': '/health/movement',
  '/health/fixed-exercise-time': '/health/movement',
  '/health/gratitude-journaling': '/health/mind',
  '/health/intermittent-fasting': '/health/nutrition',
  '/health/mindful-breathing': '/health/mind',
  '/health/morning-sunlight': '/health/rhythm',
  '/health/power-nap': '/health/sleep',
  '/health/regular-meal-times': '/health/nutrition',
  '/health/regular-sleep-schedule': '/health/sleep',
  '/health/screens-before-bed': '/health/sleep',
  '/health/seven-to-eight-hours-sleep': '/health/sleep',
  '/health/stay-hydrated': '/health/nutrition',
  '/health/time-in-nature': '/health/mind',
  '/health/work-rest-boundary': '/health/mind',
  '/stories/albert-einstein': '/stories/thinkers',
  '/stories/arianna-huffington': '/stories/modern',
  '/stories/beethoven': '/stories/writers',
  '/stories/benjamin-franklin': '/stories/thinkers',
  '/stories/bill-gates': '/stories/entrepreneurs',
  '/stories/charles-darwin': '/stories/thinkers',
  '/stories/elon-musk': '/stories/entrepreneurs',
  '/stories/ernest-hemingway': '/stories/writers',
  '/stories/haruki-murakami': '/stories/writers',
  '/stories/jeff-bezos': '/stories/entrepreneurs',
  '/stories/jeong-yak-yong': '/stories/leaders',
  '/stories/kobe-bryant': '/stories/modern',
  '/stories/maya-angelou': '/stories/writers',
  '/stories/michelle-obama': '/stories/modern',
  '/stories/oprah-winfrey': '/stories/modern',
  '/stories/steve-jobs': '/stories/entrepreneurs',
  '/stories/toni-morrison': '/stories/writers',
  '/stories/warren-buffett': '/stories/entrepreneurs',
  '/stories/winston-churchill': '/stories/leaders',
  '/stories/yi-sun-sin': '/stories/leaders',
};

/**
 * Resolve a request path to its 301 target, or null when the path is not a
 * retired article. Trailing slashes and casing are normalised so /health/Foo/
 * redirects exactly like /health/foo.
 */
export function legacyRedirectTarget(pathname: string): string | null {
  const key = pathname.replace(/\/+$/, '').toLowerCase();
  return LEGACY_REDIRECTS[key] ?? null;
}
